UrlJinja/UrlJinja/urls.py
from django.contrib import admin
from django.urls import path,include
import teacher,student


urlpatterns = [
    path('admin/', admin.site.urls),
    path('teacher/',include("teacher.urls")),
    path('student/',include("student.urls")),
]

UrlJinja/student/urls.py
from django.urls import path
from student.views import *

app_name = 'student'

urlpatterns = [
    path("rollNum/",rollNum,name="rollNum")
]

UrlJinja/teacher/urls.py
from django.urls import path
from teacher.views import *

app_name = "teacher"


urlpatterns = [
    path("result/",result,name="result")
]

UrlJinja/student/views.py
from django.shortcuts import render

# Create your views here.

def rollNum(request):
    return render(request,"rollNum.html")

UrlJinja/teacher/views.py
from django.shortcuts import render

# Create your views here.

def result(request):
    return render(request,"result.html")

UrlJinja/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>The Student is pass</h1>
    <a href="{% url 'student:rollNum' %}">Go back to enter new rollnumber</a>
</body>
</html>

UrlJinja/templates/rollNum.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        RollNum of Student - 007
    </h1>
    <a href="{% url 'teacher:result' %}">Check Result from teacher</a>
</body>
</html>